Add wrap files for brotli-1.0.7
mesonbuild/google-brotli pull request #1
Opened 2020-02-20 17:53 UTC by dcbaker

2020-02-20 23:56 UTC, legeana requested changes

2020-02-20 23:56 UTC, legeana commented on meson.build
> +dep_brotli_encoder = declare_dependency(
The common style is to use `${package}_dep`.
Here and in other places.

2020-02-20 23:56 UTC, legeana commented on meson.build
> +  'brotli',
`google-brotli`

2020-02-24 17:12 UTC, dcbaker commented
@legeana, look good now?

2020-02-24 17:19 UTC, merged

2020-02-24 17:20 UTC, legeana commented
@dcbaker looks good, thank you for updating it :)